# Start from the official Go image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code into the container
COPY . .

RUN go build -o ./cmd/habit_tracker/main ./cmd/habit_tracker/main.go

# Expose port 8080 to the outside world
EXPOSE 8080

# Run the binary app
CMD ["./cmd/habit_tracker/main"]
